# METADATA
title: "Extractives"
email: extractives@code4sa.org
description: Nigerian extractives.
baseurl: "/"
url: "http://www.code4sa.org/extractives/"

# OPEN GRAPH
og_description: Tensions, contradictions, loopholes and revenue in deepwater oil legislation.

# BUILD SETTINGS
permalink: /:categories/:year-:month-:day/:title.htm

# EXCLUDE
exclude: [README.md]

#RESOURCES USED
## Header image - something