# METADATA
title: "Between oil law and offshore oil industry"
description: "Tensions, contradictions, loopholes and revenue in deepwater oil legislation"
baseurl: "/"
url: "http://www.code4sa.org/offshore-oil/"

# OPEN GRAPH
og_description: Tensions, contradictions, loopholes and revenue in deepwater oil legislation.

# BUILD SETTINGS
permalink: /:categories/:year-:month-:day/:title.htm

# EXCLUDE
exclude: [README.md]

#RESOURCES USED
## Header image - something